### ISSUE TITLE
Fails on PYTHONOPTIMIZE=2

### ISSUE THREAD

**Issue by gtors** [pavdmyt/yaspin#26]
**Versions:**

yaspin  0.14
python 3.7

**Env variables:**
```
PYTHONOPTIMIZE=2
```

**Traceback**
```
10 99.05 Traceback (most recent call last):
#10 99.05   File "/usr/local/bin/pipenv", line 7, in <module>
#10 99.05     from pipenv import cli
#10 99.05   File "/usr/local/lib/python3.7/site-packages/pipenv/__init__.py", line 22, in <module>
#10 99.05     from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
#10 99.05   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/vistir/__init__.py", line 31, in <module>
#10 99.05     from .spin import VistirSpinner, create_spinner
#10 99.05   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/vistir/spin.py", line 19, in <module>
#10 99.05     import yaspin
#10 99.05   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/yaspin/__init__.py", line 6, in <module>
#10 99.05     from .api import kbi_safe_yaspin, yaspin
#10 99.05   File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/yaspin/api.py", line 87, in <module>
#10 99.05     _kbi_safe_doc = yaspin.__doc__.replace("yaspin", "kbi_safe_yaspin")
#10 99.05 AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by pavdmyt** [comment]
The temporary workaround is to set `PYTHONOPTIMIZE=1` (it doesn't cut docstrings). I'm planning to implement fix soon.
