### ISSUE TITLE
AssertionError in Py2 if provided Spinner.frames is a bytes sequence

### ISSUE THREAD

**Issue by pavdmyt** [pavdmyt/yaspin#7]
Consider following code:

```python
# -*- coding: utf-8 -*-
import time
from yaspin import yaspin, Spinner

sp = Spinner(["😸", "😹", "😺", "😻", "😼", "😽", "😾", "😿", "🙀"], 200)
with yaspin(sp, text="Cat!"):
    time.sleep(3)
```

Running this in Python 2.7 will result in the following exception:

```
$ python cat_example.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/2.7.14/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/var/pyenv/versions/2.7.14/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/me/PY_proj/yaspin/yaspin/yaspin.py", line 184, in _spin
    out = self._compose_out(spin_phase)
  File "/Users/me/PY_proj/yaspin/yaspin/yaspin.py", line 197, in _compose_out
    assert isinstance(frame, str)
AssertionError
```

**Comment by pavdmyt** [comment]
Fixed in Yaspin 0.7.1
